### ISSUE TITLE
PEER-Boston: schedule

### ISSUE THREAD

**Issue by esayre** [SayreLab/peerwebsite#17]
The schedule for this field school is not displaying properly from the spreadsheet.

**Comment by HaimarR** [comment]
Fixed. Please review.

**Comment by esayre** [comment]
No?  I'm still seeing bad dates on the site.

<img width="1122" alt="Screenshot 2024-06-01 at 10 09 13 AM" src="https://github.com/SayreLab/peerwebsite/assets/5422446/0c7be7f0-7475-4632-bf06-fd1fba52ab75">

Did you forget to pull / merge?

**Comment by HaimarR** [comment]
It's on the branch I'm working on, I'll merge it in a bit.

**Comment by HaimarR** [comment]
Merged it some hours ago
